# -*- coding: utf-8 -*-
"""WebScraping-Airbnb.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/141o7gnx-7bZRkU4QJAa4W7kcLHW2aOmF
"""

import requests
from bs4 import BeautifulSoup

url = 'https://www.airbnb.com.ar/s/Cordoba--Argentina/homes?tab_id=home_tab&refinement_paths%5B%5D=%2Fhomes&flexible_trip_lengths%5B%5D=one_week&monthly_start_date=2023-12-01&monthly_length=3&price_filter_input_type=0&price_filter_num_nights=5&channel=EXPLORE&query=C%C3%B3rdoba%2C%20Argentina&date_picker_type=flexible_dates&adults=1&source=structured_search_input_header&search_type=autocomplete_click&place_id=ChIJNcbaCaHULJQRnokOgQ8wLec'

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Buscar elementos que contienen el símbolo "$"
price_elements = soup.find_all(lambda tag: tag.name == 'span' and '$' in tag.text)

# Extraer la información relevante
for price_element in price_elements:
    # Obtener el nombre del departamento
    name = price_element.find_previous('h1').text.strip()

    # Obtener el precio
    price = price_element.text.strip()

    # Imprimir resultados
    print(f"Nombre: {name}, Precio: {price}")